name: flutter_news
description: Flutter News.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # C
  cached_network_image: ^3.2.0

  # D
  dio: ^4.0.4

  # F
  flutter_spinkit: ^5.1.0

  # I
  infinite_scroll_pagination: ^3.1.0

  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true